# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: econ_gcmessages.proto
# plugin: python-betterproto

from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class CMsgApplyAutograph(betterproto.Message):
    autograph_item_id: int = betterproto.uint64_field(1)
    item_item_id: int = betterproto.uint64_field(2)


@dataclass
class CMsgEconPlayerStrangeCountAdjustment(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    strange_count_adjustments: List[
        "CMsgEconPlayerStrangeCountAdjustmentCStrangeCountAdjustment"
    ] = betterproto.message_field(2)


@dataclass
class CMsgEconPlayerStrangeCountAdjustmentCStrangeCountAdjustment(betterproto.Message):
    event_type: int = betterproto.uint32_field(1)
    item_id: int = betterproto.uint64_field(2)
    adjustment: int = betterproto.uint32_field(3)


@dataclass
class CMsgRequestItemPurgatoryFinalizePurchase(betterproto.Message):
    item_ids: List[int] = betterproto.uint64_field(1)


@dataclass
class CMsgRequestItemPurgatoryFinalizePurchaseResponse(betterproto.Message):
    result: int = betterproto.uint32_field(1)


@dataclass
class CMsgRequestItemPurgatoryRefundPurchase(betterproto.Message):
    item_id: int = betterproto.uint64_field(1)


@dataclass
class CMsgRequestItemPurgatoryRefundPurchaseResponse(betterproto.Message):
    result: int = betterproto.uint32_field(1)


@dataclass
class CMsgCraftingResponse(betterproto.Message):
    item_ids: List[int] = betterproto.uint64_field(1)


@dataclass
class CMsgGcRequestStoreSalesData(betterproto.Message):
    version: int = betterproto.uint32_field(1)
    currency: int = betterproto.uint32_field(2)


@dataclass
class CMsgGcRequestStoreSalesDataResponse(betterproto.Message):
    sale_price: List["CMsgGcRequestStoreSalesDataResponsePrice"] = betterproto.message_field(1)
    version: int = betterproto.uint32_field(2)
    expiration_time: int = betterproto.uint32_field(3)


@dataclass
class CMsgGcRequestStoreSalesDataResponsePrice(betterproto.Message):
    item_def: int = betterproto.uint32_field(1)
    price: int = betterproto.uint32_field(2)


@dataclass
class CMsgGcRequestStoreSalesDataUpToDateResponse(betterproto.Message):
    version: int = betterproto.uint32_field(1)
    expiration_time: int = betterproto.uint32_field(2)


@dataclass
class CMsgGcToGcPingRequest(betterproto.Message):
    pass


@dataclass
class CMsgGcToGcPingResponse(betterproto.Message):
    pass


@dataclass
class CMsgGcToGcGetUserSessionServer(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)


@dataclass
class CMsgGcToGcGetUserSessionServerResponse(betterproto.Message):
    server_steam_id: int = betterproto.fixed64_field(1)


@dataclass
class CMsgGcToGcGetUserServerMembers(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    max_spectators: int = betterproto.uint32_field(2)


@dataclass
class CMsgGcToGcGetUserServerMembersResponse(betterproto.Message):
    member_account_id: List[int] = betterproto.uint32_field(1)


@dataclass
class CMsgLookupMultipleAccountNames(betterproto.Message):
    accountids: List[int] = betterproto.uint32_field(1)


@dataclass
class CMsgLookupMultipleAccountNamesResponse(betterproto.Message):
    accounts: List["CMsgLookupMultipleAccountNamesResponseAccount"] = betterproto.message_field(1)


@dataclass
class CMsgLookupMultipleAccountNamesResponseAccount(betterproto.Message):
    accountid: int = betterproto.uint32_field(1)
    persona: str = betterproto.string_field(2)


@dataclass
class CMsgGcToGcGrantSelfMadeItemToAccount(betterproto.Message):
    item_def_index: int = betterproto.uint32_field(1)
    accountid: int = betterproto.uint32_field(2)


@dataclass
class CMsgGcToGcThankedByNewUser(betterproto.Message):
    new_user_accountid: int = betterproto.uint32_field(1)
    thanked_user_accountid: int = betterproto.uint32_field(2)


@dataclass
class CMsgGcShuffleCrateContents(betterproto.Message):
    crate_item_id: int = betterproto.uint64_field(1)
    user_code_string: str = betterproto.string_field(2)


@dataclass
class CMsgGcQuestObjectiveProgress(betterproto.Message):
    quest_id: int = betterproto.uint64_field(1)
    quest_attrib_index: int = betterproto.uint32_field(2)
    delta: int = betterproto.uint32_field(3)
    owner_steamid: int = betterproto.fixed64_field(4)


@dataclass
class CMsgGcQuestObjectivePointsChange(betterproto.Message):
    quest_id: int = betterproto.uint64_field(1)
    owner_steamid: int = betterproto.fixed64_field(4)
    update_base_points: bool = betterproto.bool_field(5)
    points_0: int = betterproto.uint32_field(6)
    points_1: int = betterproto.uint32_field(7)
    points_2: int = betterproto.uint32_field(8)


@dataclass
class CMsgGcQuestCompleteRequest(betterproto.Message):
    quest_id: int = betterproto.uint64_field(1)


@dataclass
class CMsgGcQuestCompleted(betterproto.Message):
    pass


@dataclass
class CMsgGcQuestObjectiveRequestLoanerItems(betterproto.Message):
    quest_id: int = betterproto.uint64_field(1)


@dataclass
class CMsgGcQuestObjectiveRequestLoanerResponse(betterproto.Message):
    pass


@dataclass
class CMsgCraftCollectionUpgrade(betterproto.Message):
    item_id: List[int] = betterproto.uint64_field(1)


@dataclass
class CMsgCraftHalloweenOffering(betterproto.Message):
    tool_id: int = betterproto.uint64_field(1)
    item_id: List[int] = betterproto.uint64_field(2)


@dataclass
class CMsgCraftCommonStatClock(betterproto.Message):
    tool_id: int = betterproto.uint64_field(1)
    item_id: List[int] = betterproto.uint64_field(2)


@dataclass
class CMsgGcQuestDiscardRequest(betterproto.Message):
    quest_id: int = betterproto.uint64_field(1)
