# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: gcsystemmsgs.proto
# plugin: python-betterproto

from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class CCommunityGamePersonalDataCategoryInfo(betterproto.Message):
    type: str = betterproto.string_field(1)
    localization_token: str = betterproto.string_field(2)
    template_file: str = betterproto.string_field(3)


@dataclass
class CCommunityGetGamePersonalDataCategoriesRequest(betterproto.Message):
    appid: int = betterproto.uint32_field(1)


@dataclass
class CCommunityGetGamePersonalDataCategoriesResponse(betterproto.Message):
    categories: List["CCommunityGamePersonalDataCategoryInfo"] = betterproto.message_field(1)
    app_assets_basename: str = betterproto.string_field(2)


@dataclass
class CCommunityGetGamePersonalDataEntriesRequest(betterproto.Message):
    appid: int = betterproto.uint32_field(1)
    steamid: int = betterproto.uint64_field(2)
    type: str = betterproto.string_field(3)
    continue_token: str = betterproto.string_field(4)


@dataclass
class CCommunityGetGamePersonalDataEntriesResponse(betterproto.Message):
    gceresult: int = betterproto.uint32_field(1)
    entries: List[str] = betterproto.string_field(2)
    continue_token: str = betterproto.string_field(3)


@dataclass
class CCommunityTerminateGamePersonalDataEntriesRequest(betterproto.Message):
    appid: int = betterproto.uint32_field(1)
    steamid: int = betterproto.uint64_field(2)


@dataclass
class CCommunityTerminateGamePersonalDataEntriesResponse(betterproto.Message):
    gceresult: int = betterproto.uint32_field(1)
